name: podcast_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  kiwi: ^0.2.0
  dio: ^3.0.8
  provider: ^4.0.2
  path_provider: ^1.5.1
  package_info: ^0.4.0+13
  audioplayer: ^0.5.2
  google_fonts: ^0.3.2
  shared_preferences: ^0.5.6+1
  fluro: ^1.5.1
  transformer_page_view: ^0.1.6
  dots_indicator: ^1.1.0
  equatable: ^1.0.3
  json_annotation: ^3.0.0
  intl: ^0.16.1
  uuid: ^2.0.4
  super_enum: ^0.3.0
  sliding_up_panel: ^1.0.0

dev_dependencies:
  super_enum_generator: ^0.3.0
  build_runner: ^1.7.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
